<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="content footer-newsletter">
	<form class="form subscribe"
		novalidate
		action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
		method="post"
		data-mage-init='{"validation": {"errorClass": "mage-error"}}'
		id="newsletter-validate-detail">
            <div class="block-content">
		<div class="field newsletter ">
			
			<div class="control">
				<input class="input-text form-control" name="email" type="email" id="newsletter"
							placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
							data-validate="{required:true, 'validate-email':true}"/>
			</div>
		</div>
		<div class="actions">
			<button class="action subscribe primary btn" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                            <span class="hidden-xs"><?php /* @escapeNotVerified */ echo __('Subscribe') ?><i class="fa fa-long-arrow-right"></i></span>
                            <span class="hidden-lg hidden-md hidden-sm"><i class="fa fa-envelope-o"></i></span>
			</button>
		</div>
            </div>
	</form>
</div>
