<?php $portfolios = $this->getPortfolios() ?>
<div class="row portfolio-container">
	<?php if(count($portfolios)>0): ?>
		<?php $helper = $this->helper('MGS\Portfolio\Helper\Data') ?>
		<?php foreach($portfolios as $portfolio): ?>
			<div class="col-md-4 col-sm-4 col-xs-12 item">
				<div class="portfolio-top-content">
					<?php $thumbnailUrl = $this->getThumbnailSrc($portfolio) ?>
					<?php $portfolioUrl = $this->getPortfolioAddress($portfolio) ?>
					<?php if($thumbnailUrl): ?>
						<a href="<?php echo $portfolioUrl; ?>">
							<img src="<?php echo $thumbnailUrl ?>" alt="" class="img-responsive"/>
						</a>
					<?php endif ?>
					<span class="hover-info text-center text-colour-white button-text-colour-white">						
						<span class="project h4"><?php echo $portfolio->getServices() ?></span>
					</span>
				</div>
				<div class="portfolio-bottom-content">
					<h4><a href="<?php echo $portfolioUrl; ?>"><?php echo $portfolio->getName() ?></a></h4>
					<p class="category-link"><?php echo $this->getCategoriesLink($portfolio) ?></p>
				</div>
			</div>
		<?php endforeach ?>
	<?php else: ?>
		<p class="note-msg"><?php echo $this->__('There are no portfolios matching the selection.') ?></p>
	<?php endif ?>
</div>