<?php
/**
 * @category    Fishpig
 * @package     FishPig_WordPress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <ben@fishpig.co.uk>
 */
?>
<?php if ($post = $this->getPost()): ?>
	<div class="post-view">
		<div class="post-entry">
			<?php if ($image = $post->getImage()): ?>
				<div class="post-image">
<?php $mainImage = $image->getAvailableImage();
      $ext = pathinfo($mainImage, PATHINFO_EXTENSION);

      $expImage = explode('.'.$ext,"$mainImage");
     // print_r($expImage);  
     $final = substr($expImage[0], 0, -8); 
     $finalImage = $final.'.'.$ext;
 ?>
					<a href="<?php echo $post->getUrl() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><img src="<?php echo $finalImage; ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/></a>
				</div>
			<?php endif; ?>
			<?php if (($content = trim($post->getContent())) !== ''): ?>
				<div class="post-content"><?php echo $content ?></div>
			<?php endif; ?>
		</div>
		<?php echo $this->getChildHtml('comments') ?>
	</div>
<?php endif; ?>
