<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>

<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $conditions = $this->getData('conditions_encoded') ? $this->getData('conditions_encoded') : $this->getData('conditions');?>
<?php $checkAttribute = $themeHelper->checkAttributeExist($conditions); ?>
<?php if($checkAttribute['result']=='error'): ?>
	<div class="alert alert-danger no-product-display">
        <p><?php echo __('There are no products matching the selection. Attribute %1 is not exist.', $checkAttribute['attribute']) ?></p>
    </div>
<?php else: ?>

	<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>

		<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>

		<?php $themeSettings = $themeHelper->getThemeSettings(); ?>
		<?php
			$type = 'widget-product-grid';

			$mode = 'grid';
			$imageTwo = 'new_products_content_widget_grid_two';
			$image = 'new_products_content_widget_grid';
			$title = $block->getTitle() ? __($block->getTitle()) : '';
			$items = $block->getProductCollection()->getItems();

			$showWishlist = true;
			$showCompare = true;
			$showCart = true;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
			$description = false;
		?>
		<?php if($this->getData('per_row') != null){
			$perRow = $this->getData('per_row');
		}else {
			$perRow = $themeSettings['catalog']['per_row'];
		} ?>
		<div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
			<?php if ($title):?>
				<div class="title-content">
					<h3><?php /* @escapeNotVerified */ echo $title; ?></h3>
				</div>
			<?php endif ?>
			<div class="block-content">
				<?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
				<div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
					<ol class="product-items products-grid row <?php /* @escapeNotVerified */ echo $type; ?>">
						<?php $iterator = 1; ?>
						<?php foreach ($items as $_item): ?>
							<?php $_productNameStripped = $block->stripTags($_item->getName(), null, true); ?>
							<?php
								$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
								$size = $themeHelper->getImageSize();
								$productImage = $_imagehelper->init($_item, $image)->resize($size['width'], $size['height'])->getUrl();
							?>
							<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item '. $themeHelper->getColClass($perRow) .'">' : '<li class="item product product-item '. $themeHelper->getColClass($perRow) .'">' ?>
							<div class="product-item-info product-content">
								<div class="product-top">
									<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo product-image">
										<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>
										<?php if(basename($_item->getData('image')) !=  'no_selection'): ?>
											<?php if(basename($_item->getData('image')) != basename($_item->getData('small_image'))): ?>
												<?php $productImageTwo = $_imagehelper->init($_item, $imageTwo)->resize($size['width'], $size['height'])->getUrl(); ?>
												<img src="<?php echo $productImageTwo; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive img-two product-image-photo"/>
											<?php endif ?>
										<?php endif ?>
									</a>
									<?php if ($templateType): ?><?php echo $block->getReviewsSummaryHtml($_item, $templateType,true) ?><?php endif; ?>
									<?php if ($showWishlist || $showCompare): ?>
										<ul class="icon-links" data-role="add-to-links">
											<li class="li-quickview">
												<?php /* Append Quick View */ ?>
												<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
												<?php echo $quickViewHelper->aroundQuickViewHtml($_item); ?>
											</li>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
												<li>
													<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
													   class="action towishlist" data-action="add-to-wishlist"
													   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
														<em class="fa fa-heart"></em>
													</a>
												</li>
											<?php endif ?>
											<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
												<li><a href="#" class="action tocompare"
												   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
												   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
													<em class="fa fa-retweet"></em>
												</a></li>
											<?php endif; ?>
										</ul>
									<?php endif ?>
								</div>
								<div class="product-desc">
									<h6 class="product-name">
										<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
										   href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
										   class="product-item-link">
											<?php echo $block->escapeHtml($_item->getName()) ?>
										</a>
									</h6>
									<?php echo $block->getProductPriceHtml($_item, $type); ?>
									<?php if ($showCart): ?>
										<div class="controls">
											<div class="add-to-cart">
												<?php if ($_item->isSaleable()): ?>
													<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
														<button class="tocart btn-cart"
																data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
																type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
															<i class="fa fa-shopping-cart"></i>
														</button>
													<?php else: ?>
														<?php
															$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
															$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
														?>
														<button class="tocart btn-cart"
																data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
															<i class="fa fa-shopping-cart"></i>
														</button>
													<?php endif; ?>
												<?php else: ?>
													<?php if ($_item->getIsSalable()): ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
										</div>
									<?php endif ?>
								</div>
							</div>
							</li>
						<?php endforeach ?>
					</ol>
				</div>
				<?php echo $block->getPagerHtml() ?>
			</div>
		</div>
	<?php else: ?>
		<div class="alert alert-danger no-product-display">
			<p><?php echo __('There are no products matching the selection.') ?></p>
		</div>
	<?php endif;?>
<?php endif;?>
