<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $conditions = $this->getData('conditions_encoded') ? $this->getData('conditions_encoded') : $this->getData('conditions');?>
<?php $checkAttribute = $themeHelper->checkAttributeExist($conditions); ?>
<?php if($checkAttribute['result']=='error'): ?>
	<div class="alert alert-danger no-product-display">
        <p><?php echo __('There are no products matching the selection. Attribute %1 is not exist.', $checkAttribute['attribute']) ?></p>
    </div>
<?php else: ?>
	<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
		<?php
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
			$themeSettings = $themeHelper->getThemeSettings();
			$type = 'widget-product-grid';

			$mode = 'grid';

			$image = 'new_products_content_widget_list';
			$title = $block->getTitle() ? __($block->getTitle()) : '';
			$items = $block->getProductCollection()->getItems();

			$showWishlist = true;
			$showCompare = true;
			$showCart = true;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
			$description = false;
		?>
		<div class="product-block-list">
			<div class="products <?php /* @escapeNotVerified */ echo $mode; ?> list-content">
				<div class="boxed-content padding30">
					<?php if ($title):?>
						<div class="title-block">
							<h4><?php /* @escapeNotVerified */ echo $title; ?></h4>
						</div>
					<?php endif ?>
					<ol class="row product-items <?php /* @escapeNotVerified */ echo $type; ?>">
						<?php $i=0; foreach ($items as $_item): $i++; ?>
							<?php $_productNameStripped = $block->stripTags($_item->getName(), null, true); ?>
							<li class="item col-md-12 col-sm-6 col-xs-12 col-sm-half <?php if($i % 2 == 1): ?>row-2sm-first row-2xs-first<?php endif ?>">
								<div class="product-content">
									<div class="product-left">
									<?php 	$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
											$size = $themeHelper->getImageSize();
											$ratio = $size['width']/$size['height'];
											$height = 150/$ratio;
											$productImage = $_imagehelper->init($_item, $image)->resize(150, $height)->getUrl(); ?>
										<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo product-image">
											<img class="img-responsive" alt="<?php echo $_productNameStripped ?>" src="<?php echo $productImage; ?>" />
										</a>
									</div>
									<div class="product-right">
										<h5 class="product-name"><a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
											   href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
											   class="product-item-link">
												<?php echo $block->escapeHtml($_item->getName()) ?>
											</a></h5>
										<?php echo $block->getProductPriceHtml($_item, $type); ?>
										<?php if ($showWishlist || $showCompare || $showCart): ?>
											<ul class="icon-links">
												<?php if ($showCart): ?>
													<li class="add-to-cart">
														<?php if ($_item->isSaleable()): ?>
															<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																<button class="btn-cart action tocart"
																		data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
																		type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span><i class="fa fa-shopping-cart"></i></span>
																</button>
															<?php else: ?>
																<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																	$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]) ?>
																<button class="action tocart btn-cart"
																		data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																		type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span><i class="fa fa-shopping-cart"></i></span>
																</button>
															<?php endif; ?>
														<?php else: ?>
															<?php if ($_item->getIsSalable()): ?>
																<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
															<?php else: ?>
																<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
															<?php endif; ?>
														<?php endif; ?>
													</li>
												<?php endif ?>
												<?php if ($showWishlist || $showCompare): ?>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
														<li><a href="#"
														   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
														   class="action towishlist" data-action="add-to-wishlist"
														   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
															<em class="fa fa-heart"></em>
														</a></li>
													<?php endif; ?>
													<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
														<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
														<li><a href="#" class="action tocompare"
														   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
														   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
															<span><em class="fa fa-retweet"></em></span>
														</a></li>
													<?php endif; ?>
												<?php endif; ?>
												<li class="clear"></li>
											</ul>
										<?php endif ?>
									</div>
									<div class="clear"></div>
								</div>
							</li>
						<?php endforeach ?>
					</ol>
				</div>
				<?php if($this->getData('category_show') != ''): ?>
					<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
					<?php $currentCate = $objectManager->create('Magento\Catalog\Model\Category')->load($this->getData('category_show')); ?>
					<button onclick="setLocation('<?php echo $currentCate->getUrl(); ?>')" class="btn btn-full btn-go-cate"><?php echo __('View More') ?>&nbsp;&nbsp;<span class="fa fa-long-arrow-right"></span></button>
				<?php endif ?>
			</div>
		</div>
	<?php else: ?>
		<div class="alert alert-danger no-product-display">
			<p><?php echo __('There are no products matching the selection.') ?></p>
		</div>
	<?php endif;?>
<?php endif;?>