<?php
/**
 * @category FishPig
 * @package FishPig_WordPress
 * @notes This template is used when there post/list.phtml doesn't have a child block called 'renderer'
 * @notes This happens when post/list.phtml is called in via PHP rather than via the default layout handles
 */
?>
<?php if ($post = $this->getPost()): ?>
	<div class="post-list-item">
		<div class="blog-post-box" style="background-image: url('<?php if ($image = $post->getImage()): ?> <?php echo $image->getAvailableImage() ?> <?php endif; ?>')">  
			<div class="post-dtls">
				<h2 class="post-title">
					<a href="<?php echo $post->getUrl() ?>" title="<?php echo $this->escapeHtml($post->getName()) ?>">
						<?php echo $this->escapeHtml($post->getName()) ?>
					</a>
				</h2>
				<div class="post-date">
					<?php echo $post->getPostDate() ?>
				</div> 
				<div class="read-more text-right text-uppercase"> 
					<a href="<?php echo $post->getUrl() ?>">Read more</a>
				</div>
			</div>
		</div> 
	</div>
<?php endif; ?>