<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>

<div class="products-grid wishlist form-group">
    <?php $iterator = 1; ?>
    <?php if (count($block->getItems())): ?>
    <ol class="product-items">
        <?php foreach ($block->getItems() as $item): ?>
        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li data-row="product-item" class="product-item" id="item_' . $item->getId() . '">' : '</li><li class="product-item" id="item_' . $item->getId() . '">' ?>
            <div class="product-item-info row">
                <div class="table-responsive">
                    <table class="table table-hover table-condensed wishlist-table">
                        <thead>
                            <tr class="first last">
                                <th></th>
                                <th><?php echo __('Product Details and Comment')?></th>
                                <th><?php echo __('Price')?></th>
                                <th><?php echo __('Add to cart')?></th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            <tr>
                                <?php foreach ($columns as $column): ?>                           
                                <?php $column->setItem($item);?>                                
                                <td>
                                    <?php echo $column->toHtml($item);?>
                                </td>
                                <?php endforeach; ?>
                            </tr>
                            
                               
                            
                        </tbody>
                    </table>
                </div>
                
            </div>
        <?php echo($iterator == count($block->getItems())+1) ? '</li>' : '' ?>
        <?php endforeach; ?>
    </ol>
    <?php else: ?>
        <div class="message info empty">
            <span><?php /* @escapeNotVerified */ echo __('This Wish List has no Items');?></span>
        </div>
    <?php endif; ?>
</div>

<?php foreach ($columns as $column): ?>
    <?php echo $column->getAdditionalHtml();?>
<?php endforeach; ?>
