<?php $block = $this->getBlock() ?>
<?php $mpanel = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $welcomeMessage = $block->getWelcome(); ?>
<div class="header-v2<?php if ($mpanel->getStoreConfig('mgstheme/general/sticky_menu')): ?> sticky-menu<?php endif; ?>">
	<div class="top-header-content header-v2">
		<div class="container">
			<div class="row">
				<div class="col-md-5 col-sm-3 col-xs-6" data-bind="scope: 'customer'">
					<span class="h6" data-bind="text: customer().fullname ? $t('Welcome, %1!').replace('%1', customer().fullname) : '<?php echo $block->escapeHtml($welcomeMessage) ?>'"><?php echo $block->escapeHtml($welcomeMessage) ?></span>				</div>
				<div class="col-md-7 col-sm-9 col-xs-6">
					<div class="h6 account-top-link">
						 <div class="dropdown">
							  <button class="dropdown-toggle" type="button" data-toggle="dropdown"><?php echo __('My Account') ?>&nbsp;<i class="fa fa-angle-down"></i></button>
							<?php echo $block->getChildHtml('top.links') ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="middle-header-content">
		<div class="container text-center">
			 <div class="logo-container"><?php echo $block->getChildHtml('logo') ?></div>
		</div>
	</div>
	<div class="header-menu">
		<div class="container">
			<button class="btn btn-responsive-nav btn-inverse">
				<i class="fa fa-bars"></i>
			</button>
			<div class="megamenu-content navbar-collapse">
				<?php echo $block->getChildHtml('megamenu') ?>
			</div>
			<div class="top-links header-top">
				<?php echo $block->getChildHtml('top.search.mini') ?>
				<?php echo $block->getChildHtml('minicart') ?>
				<?php echo $block->getChildHtml('store_language') ?>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
            require([
                'jquery'
            ], function ($) {
                $(document).ready(function () {
					$('.header-v2 .account-top-link ul').addClass('dropdown-menu');
				});
            });
        </script>