<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $header = $helper->getStoreConfig('mgstheme/general/header') ?>
<?php if($header!=''): ?>
	<?php echo $this->getLayout()->createBlock('Magento\Theme\Block\Html\Header')->setBlock($block)->setTemplate('Magento_Theme::html/headers/'.$header.'.phtml')->toHtml() ?>
<?php else: ?>
	<?php $welcomeMessage = $block->getWelcome(); ?>
	<div class="top-header-content header-v1">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-5 dol-xs-12">
					<div class="greet welcome" data-bind="scope: 'customer'">
						<span data-bind="text: customer().fullname ? $t('Welcome, %1!').replace('%1', customer().fullname) : '<?php echo $block->escapeHtml($welcomeMessage) ?>'"><?php echo $block->escapeHtml($welcomeMessage) ?></span>
					</div>
				</div>
				<div class="col-md-8 col-sm-7 dol-xs-12">
					<?php echo $block->getChildHtml('top.links') ?>
					<?php echo $block->getChildHtml('currency') ?>
					<?php echo $block->getChildHtml('store_language') ?>
				</div>
			</div>
		</div>
	</div>
	<div class="middle-header-content">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-3 col-xs-12"><?php echo $block->getChildHtml('logo') ?></div>
				<div class="col-md-7 col-sm-7 col-xs-12"><?php echo $block->getChildHtml('topSearch') ?></div>
				<div class="col-md-2 col-sm-2 col-xs-12 cart-mobile"><?php echo $block->getChildHtml('minicart') ?></div>
			</div>
		</div>
	</div>
	<?php echo $block->getChildHtml('megamenu') ?>
<?php endif ?>