<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
<div class="hidden-bottom">
    <?php echo $block->getToolbarHtml() ?>
</div>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
		$imageTwo = 'category_page_two_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
		$imageTwo = 'category_page_two_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items row <?php if($block->getMode() != 'grid'): ?>category-products-list<?php endif ?>">
            <?php $i =0;  foreach ($_productCollection as $_product): $i++; ?>
				<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
				<?php
					$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
					$size = $themeHelper->getImageSize();
					$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
				?>
				<?php if ($block->getMode() == 'grid'):?>
					<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item '. $themeHelper->getColClass($themeSettings['catalog']['per_row']) .'">' : '</li><li class="item product product-item '. $themeHelper->getColClass($themeSettings['catalog']['per_row']) . $themeHelper->getClearClass($themeSettings['catalog']['per_row'], $i) .'">' ?>
						<div class="product-item-info" data-container="product-grid">
							<div class="product-content">
								<div class="product-top">
									<?php // Product Image ?>
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo product-image" tabindex="-1">
										<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>
										<?php if(basename($_product->getData('image')) !=  'no_selection'): ?>
											<?php if(basename($_product->getData('image')) != basename($_product->getData('small_image'))): ?>
												<?php $productImageTwo = $_imagehelper->init($_product, $imageTwo)->resize($size['width'], $size['height'])->getUrl(); ?>
												<img src="<?php echo $productImageTwo; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive img-two product-image-photo"/>
											<?php endif ?>
										<?php endif ?>
									</a>
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
									<?php echo $themeHelper->getProductLabel($_product) ?>
									<?php if(!$themeSettings['catalog']['wishlist_button'] || !$themeSettings['catalog']['compare_button']): ?>
										<ul data-role="add-to-links" class="icon-links">
											<li class="li-quickview">
												<?php /* Append Quick View */ ?>
												<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
												<?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
											</li>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
												<li><a href="#"
												   class="action towishlist"
												   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
												   data-action="add-to-wishlist"
												   role="button">
													<i class="fa fa-heart"></i>
												</a></li>
											<?php endif; ?>
											<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
											<?php if(!$themeSettings['catalog']['compare_button']): ?>
												<li><a href="#"
												   class="action tocompare"
												   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
												   role="button">
													<i class="fa fa-retweet"></i>
												</a></li>
											<?php endif ?>
										</ul>
									<?php endif ?>
								</div>
								<div class="product-desc product details product-item-details">
									<h6 class="product-name product-item-name">
										<a class="product-item-link"
										   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h6>
									<?php echo $block->getProductDetailsHtml($_product); ?>
									<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
									<div class="information-prd ">
										<?php if ($showDescription):?>
											<div class="product description product-item-description">
												<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
												   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
											</div>
										<?php endif; ?>
									</div>
									<div class="controls">
										<div class="add-to-cart">
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit"
															title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
															class="action tocart btn-cart">
														<span><span class="fa fa-shopping-cart"></span></span>
													</button>
												</form>
											<?php else: ?>
												<?php if ($_product->getIsSalable()): ?>
													<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					<?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
				<?php else:?>
					<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item col-md-12 col-sm-12 col-xs-12">' : '</li><li class="item product product-item col-md-12 col-sm-12 col-xs-12">' ?>
					<div class="product-item-info" data-container="product-grid">
						<div class="row">
							<div class="col-md-3 col-sm-6 col-xs-12">
								<div class="product-images-box">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-image product photo product-item-photo" tabindex="-1">
										<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>
									</a>
									<?php echo $themeHelper->getProductLabel($_product) ?>
								</div>
							</div>
							<div class="col-md-9 col-sm-6 col-xs-12">
								<h6 class="product name product-item-name">
									<a class="product-item-link"
									   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h6>
								<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
								<?php echo $block->getProductDetailsHtml($_product); ?>
								<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
								
								<div class="product description product-item-description">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
								</div>
								<div class="controls">
									<ul class="icon-links">
										<li class="actions-primary add-cart-item">
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit"
															title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
															class="btn btn-cart btn-default btn-lg">
														<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>
												</form>
											<?php else: ?>
												<?php if ($_product->getIsSalable()): ?>
													<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</li>
										<li class="li-quickview">
											<?php /* Append Quick View */ ?>
											<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
											<?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
										</li>
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
											<li><button
											   class="action towishlist"
											   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
											   data-action="add-to-wishlist"
											   role="button">
												<i class="fa fa-heart"></i>
											</button></li>
										<?php endif; ?>
										<?php if(!$themeSettings['catalog']['compare_button']): ?>
											<li><?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
												<button
												   class="action tocompare"
												   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
												   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
												   role="button">
													<i class="fa fa-retweet"></i>
												</button>
											</li>
										<?php endif ?>
								</div>
							</div>
						</div>
					</div>
					<?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
				<?php endif;?>
            <?php endforeach; ?>
        </ol>
    </div>
<div class="hidden-top">
    <?php echo $block->getToolbarHtml() ?>
</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
