<?php
$helper = $this->helper('MGS\Blog\Helper\Data');
$post = $block->getCurrentPost();
$showThumbnail = $this->getConfig('general_settings/show_thumbnail');
$showImage = $this->getConfig('general_settings/show_image');
if ($this->getConfig('general_settings/thumbnail_width') != '') {
    $width = $this->getConfig('general_settings/thumbnail_width');
} else {
    $width = 240;
}
if ($this->getConfig('general_settings/thumbnail_height') != '') {
    $height = $this->getConfig('general_settings/thumbnail_height');
} else {
    $height = 180;
}
?>
<div class="blog-post post-detail-content">
	<div class="post-info">
		<div class="day-desc">
			<strong class="number h3"><?php echo date('d', strtotime($block->formatDate($post->getCreatedAt(), \IntlDateFormatter::MEDIUM, false))) ?></strong>
			<span class="text h6 text-uppercase"><?php echo date('M', strtotime($block->formatDate($post->getCreatedAt(), \IntlDateFormatter::MEDIUM, false))) ?></span>
		</div>
		<?php if ($this->getConfig('comment_settings/enabled')): ?>
			<?php $manyCm = ""; ?><?php if($post->getCommentCount() > 1){ $manyCm = "s"; } ?>
			<div class="timer">
				<strong class="number h3"><?php echo $post->getCommentCount(); ?></strong>
				<span class="text h6"><?php echo __('Comment%1', $manyCm) ?></span>
			</div>
		<?php endif; ?>
		<div class="clear"></div>
	</div>
	<?php if ($showImage): ?>
		<div class="post-image">
			<img class="img-responsive" alt="<?php echo $post->getTitle(); ?>"
				 src="<?php echo $post->getImageUrl(); ?>">
		</div>
	<?php endif; ?>
	<div class="postDetails h6">
		<?php $categories = $post->getCatetories(); ?>
		<?php if (count($categories)): ?>
			<?php echo __('Posted in ') ?><?php foreach ($categories as $category): ?>
				<a title="<?php echo $category->getTitle(); ?>" href="<?php echo $category->getCategoryUrl(); ?>"><?php echo $category->getTitle(); ?></a>
			<?php endforeach; ?>
			<?php if ($post->getUpdatedByUser()): ?>
				<?php echo __(' By %1', $post->getUpdatedByUser()); ?>
			<?php else: ?>
				<?php echo __(' By %1', $post->getUser()); ?>
			<?php endif; ?>
		<?php endif ?>
	</div>
    <?php if ($post->getTags()): ?>
        <?php $tags = explode(',', $post->getTags()); ?>
        <div class="post-tags tagcloud">
            <strong><?php echo __('Tags: '); ?></strong>
            <?php foreach ($tags as $tag): ?>
                <a title="<?php echo trim($tag); ?>" href="<?php echo $helper->getTagUrl(trim($tag)); ?>"><?php echo trim($tag); ?></a>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if ($post->getContent()): ?>
        <div class="post-content">
            <?php echo $post->getContent(); ?>
        </div>
    <?php endif; ?>
	 <?php if ($this->getConfig('general_settings/use_sharethis')): ?>
        <div class="post-sharethis">
			<span class="title"> <?php echo __('Share This: ') ?></span>
            <span class='st_facebook' st_url='<?php echo $block->getPostUrl(); ?>' st_title='<?php echo $post->getTitle(); ?>' displayText='<?php echo __('Facebook'); ?>'></span>
            <span class='st_googleplus' st_url='<?php echo $block->getPostUrl(); ?>' st_title='<?php echo $post->getTitle(); ?>' displayText='<?php echo __('Google +'); ?>'></span>
            <span class='st_twitter' st_url='<?php echo $block->getPostUrl(); ?>' st_title='<?php echo $post->getTitle(); ?>' displayText='<?php echo __('Tweet'); ?>'></span>
            <span class='st_linkedin' st_url='<?php echo $block->getPostUrl(); ?>' st_title='<?php echo $post->getTitle(); ?>' displayText='<?php echo __('LinkedIn'); ?>'></span>
            <span class='st_pinterest' st_url='<?php echo $block->getPostUrl(); ?>' st_title='<?php echo $post->getTitle(); ?>' displayText='<?php echo __('Pinterest'); ?>'></span>
            <span class='st_email' st_url='<?php echo $block->getPostUrl(); ?>' st_title='<?php echo $post->getTitle(); ?>' displayText='<?php echo __('Email'); ?>'></span>
        </div>
    <?php endif; ?>
    <?php echo $block->getChildHtml('post_view_comment'); ?>
</div>
